"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, ChartNoAxesColumnIncreasing, ChevronLeft, Clock3, Dices, LibraryBig, PenLine, Plus, Search, Trash2, Users, X } from "lucide-react";

type Game = { id:number; name:string; coverPath:string|null; minPlayers:number; maxPlayers:number; estimatedMinutes:number|null; avgDuration:number|null; difficulty:string|number|null; rating:number|null; notes:string|null; rulesUrl:string|null; tags:string[]; playedCount:number };
type Player = { id:number; name:string };
type Session = { gameId:number; players:number[]; startedAt:number|null };
type DifficultyFilter = "all"|"veryEasy"|"easy"|"medium"|"hard";
type TagMode = "include"|"exclude";
type Rule = { id:number; title:string; content:string; type?:"section"|"pdf"; page?:number; filePath?:string };
type Rules = { sections:Rule[]; documents:{id:number;fileName:string;filePath:string}[]; results:Rule[] };
type Stats = {
  total:number;
  totalWins:number;
  topGames:{name:string;plays:number}[];
  players:{id:number;name:string;plays:number;wins:number;winRate:number|null}[];
};
type GameStats = {
  total:number;
  averageScore:{value:number|null;count:number};
  scoresByPlayerCount:{playerCount:number;averageScore:number;scoreCount:number}[];
  players:{id:number;name:string;plays:number;wins:number;averageScore:number|null;scoreCount:number}[];
};

const blankRules:Rules={sections:[],documents:[],results:[]};
const difficultyOptions:[DifficultyFilter,string][]=[["all","Peu importe"],["veryEasy","Très facile"],["easy","Facile"],["medium","Intermédiaire"],["hard","Exigeant"]];
const json=async<T,>(url:string,options?:RequestInit):Promise<T>=>{const response=await fetch(url,options);const body=await response.json();if(!response.ok)throw new Error(body.error||"Une erreur est survenue.");return body as T};
const send=(body:unknown,method="POST"):RequestInit=>({method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
const elapsed=(seconds:number)=>{const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return [h,m,s].map(value=>String(value).padStart(2,"0")).join(":")};
const difficultyValue=(game:Game)=>Number(game.difficulty)||0;
const difficultyLabel=(value:number)=>value<=1.3?"Très facile":value<=2?"Facile":value<=2.6?"Intermédiaire":"Exigeant";
const matchesDifficulty=(game:Game,filter:DifficultyFilter)=>{const value=difficultyValue(game);return filter==="all"||!!value&&(filter==="veryEasy"?value<=1.3:filter==="easy"?value>1.3&&value<=2:filter==="medium"?value>2&&value<=2.6:value>2.6)};
const matchesTags=(game:Game,filters:Record<string,TagMode>)=>{const included=Object.keys(filters).filter(tag=>filters[tag]==="include"),excluded=Object.keys(filters).filter(tag=>filters[tag]==="exclude");return(!included.length||included.some(tag=>game.tags.includes(tag)))&&!excluded.some(tag=>game.tags.includes(tag))};
const formatNumber=(value:number)=>value.toLocaleString("fr-FR",{maximumFractionDigits:2});
const plural=(count:number,word:string)=>`${count} ${word}${count===1?"":"s"}`;
const compressCover=async(file:File):Promise<File>=>{if(!file.type.startsWith("image/"))return file;const image=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext("2d");if(!context){image.close();return file}context.drawImage(image,0,0,canvas.width,canvas.height);image.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.82));return blob&&blob.size<file.size?new File([blob],"cover.jpg",{type:"image/jpeg"}):file};

function Cover({game,large=false}:{game:Game;large?:boolean}) {
  const [failed,setFailed]=useState(false);
  useEffect(()=>setFailed(false),[game.coverPath]);
  return <div className={`cover${large?" cover-large":""}${game.coverPath&&!failed?" has-image":""}`} aria-label={`Boîte de ${game.name}`} role="img">
    {game.coverPath&&!failed?<img src={game.coverPath} alt="" loading={large?"eager":"lazy"} decoding="async" fetchPriority={large?"high":"low"} onError={()=>setFailed(true)}/>:<span>{game.name}</span>}
  </div>;
}

export default function FamilyApp() {
  const [tab,setTab]=useState<"play"|"games"|"stats">("play");
  const [games,setGames]=useState<Game[]>([]),[players,setPlayers]=useState<Player[]>([]),[selected,setSelected]=useState<Game|null>(null);
  const [count,setCount]=useState(4),[duration,setDuration]=useState<number|null>(null),[difficulty,setDifficulty]=useState<DifficultyFilter>("all"),[picked,setPicked]=useState<Game|null>(null);
  const [tagFilters,setTagFilters]=useState<Record<string,TagMode>>({});
  const [editingTags,setEditingTags]=useState<string[]>([]),[newTag,setNewTag]=useState("");
  const [searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState(""),[libraryDifficulty,setLibraryDifficulty]=useState<DifficultyFilter>("all"),[editor,setEditor]=useState<"new"|"edit"|null>(null);
  const [picker,setPicker]=useState(false),[finishing,setFinishing]=useState(false),[replayPrompt,setReplayPrompt]=useState(false),[chosen,setChosen]=useState<number[]>([]),[winners,setWinners]=useState<number[]>([]),[scores,setScores]=useState<Record<number,string>>({}),[newPlayer,setNewPlayer]=useState(""),[playerSearch,setPlayerSearch]=useState("");
  const [session,setSession]=useState<Session|null>(null),[lastPlay,setLastPlay]=useState<Session|null>(null),[now,setNow]=useState(Date.now());
  const [rules,setRules]=useState<Rules>(blankRules),[ruleQuery,setRuleQuery]=useState(""),[debouncedRuleQuery,setDebouncedRuleQuery]=useState(""),[addingRule,setAddingRule]=useState(false),[stats,setStats]=useState<Stats|null>(null),[gameStats,setGameStats]=useState<GameStats|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState("");

  const refresh=async()=>{const [nextGames,nextPlayers]=await Promise.all([json<Game[]>("/api/games"),json<Player[]>("/api/players")]);setGames(nextGames);setPlayers(nextPlayers);setSelected(current=>current?nextGames.find(game=>game.id===current.id)||null:null)};
  useEffect(()=>{refresh().catch(reason=>setError(reason.message));const saved=localStorage.getItem("active-play");if(saved)try{setSession(JSON.parse(saved))}catch{localStorage.removeItem("active-play")}if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(session)localStorage.setItem("active-play",JSON.stringify(session))},[session]);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedRuleQuery(ruleQuery),250);return()=>window.clearTimeout(timer)},[ruleQuery]);
  useEffect(()=>{if(!selected)return;json<Rules>(`/api/rules?gameId=${selected.id}${debouncedRuleQuery?`&q=${encodeURIComponent(debouncedRuleQuery)}`:""}`).then(setRules).catch(reason=>setError(reason.message))},[selected,debouncedRuleQuery]);
  useEffect(()=>{if(!selected)return;json<GameStats>(`/api/stats?gameId=${selected.id}`).then(setGameStats).catch(reason=>setError(reason.message))},[selected?.id,selected?.playedCount]);
  useEffect(()=>{if(tab==="stats")json<Stats>("/api/stats").then(setStats).catch(reason=>setError(reason.message))},[tab]);

  const allTags=useMemo(()=>[...new Set(games.flatMap(game=>game.tags))].sort((a,b)=>a.localeCompare(b,"fr")),[games]);
  const editorTagChoices=useMemo(()=>[...new Set([...allTags,...editingTags])],[allTags,editingTags]);
  const compatible=useMemo(()=>games.filter(game=>game.minPlayers<=count&&game.maxPlayers>=count&&matchesDifficulty(game,difficulty)&&matchesTags(game,tagFilters)&&(!duration||(game.estimatedMinutes!==null&&(duration===30?game.estimatedMinutes<30:duration===60?game.estimatedMinutes>=30&&game.estimatedMinutes<=60:game.estimatedMinutes>60)))),[games,count,duration,difficulty,tagFilters]);
  const visibleGames=useMemo(()=>games.filter(game=>game.name.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr"))&&matchesDifficulty(game,libraryDifficulty)),[games,search,libraryDifficulty]);
  const availablePlayers=useMemo(()=>players.filter(player=>!chosen.includes(player.id)&&player.name.toLocaleLowerCase("fr").includes(playerSearch.trim().toLocaleLowerCase("fr"))),[players,chosen,playerSearch]);
  const hasIndexedExternalPdf=!!selected?.rulesUrl&&rules.documents.some(document=>document.filePath===selected.rulesUrl);
  const pick=()=>setPicked(compatible[Math.floor(Math.random()*compatible.length)]||null);
  const cycleTag=(tag:string)=>setTagFilters(current=>{const next={...current};if(!next[tag])next[tag]="include";else if(next[tag]==="include")next[tag]="exclude";else delete next[tag];return next});
  const openEditor=(mode:"new"|"edit")=>{setEditingTags(mode==="edit"?selected?.tags||[]:[]);setNewTag("");setEditor(mode)};
  const toggleEditingTag=(tag:string)=>setEditingTags(current=>current.includes(tag)?current.filter(item=>item!==tag):[...current,tag]);
  const addEditingTag=()=>{const value=newTag.trim(),tag=allTags.find(item=>item.localeCompare(value,"fr",{sensitivity:"base"})===0)||value;if(tag)setEditingTags(current=>current.includes(tag)?current:[...current,tag]);setNewTag("")};
  const open=(game:Game)=>{setSelected(game);setGameStats(null);setRuleQuery("");setDebouncedRuleQuery("");setError("")};
  const clearSession=()=>{localStorage.removeItem("active-play");setSession(null);setFinishing(false);setWinners([]);setScores({})};
  const cancelPlay=()=>{if(confirm("Annuler cette partie et son chrono ?"))clearSession()};

  const addPlayer=async(event:React.FormEvent)=>{event.preventDefault();if(!newPlayer.trim())return;try{const player=await json<Player>("/api/players",send({name:newPlayer.trim()}));setPlayers(current=>[...current,player].sort((a,b)=>a.name.localeCompare(b.name,"fr")));setChosen(current=>[...current,player.id]);setNewPlayer("");setPlayerSearch("");setError("")}catch(reason){setError((reason as Error).message)}};
  const start=()=>{if(!selected||!chosen.length)return;const next={gameId:selected.id,players:chosen,startedAt:Date.now()};setSession(next);setPicker(false);setFinishing(false);setNow(Date.now())};
  const recordFinished=()=>{if(!selected||!chosen.length)return;setSession({gameId:selected.id,players:chosen,startedAt:null});setPicker(false);setFinishing(true)};
  const savePlay=async()=>{if(!session||busy)return;setBusy(true);try{const participants=session.players.map(id=>{const raw=scores[id]?.trim();return{id,winner:winners.includes(id),...(raw?{score:Number(raw)}:{})}});await json("/api/plays",send({gameId:session.gameId,duration:session.startedAt?Math.max(1,Math.round((Date.now()-session.startedAt)/60000)):null,players:participants}));setLastPlay(session);clearSession();setChosen([]);await refresh();setReplayPrompt(true);setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const replay=()=>{if(!lastPlay)return;const next={gameId:lastPlay.gameId,players:lastPlay.players,startedAt:Date.now()};setSession(next);setChosen(next.players);setReplayPrompt(false);setNow(Date.now())};

  const upload=async(file:File)=>{let uploadFile=file;try{uploadFile=await compressCover(file)}catch{}const form=new FormData();form.append("file",uploadFile);return json<{path:string;name:string}>("/api/media",{method:"POST",body:form})};
  const saveGame=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);try{const form=new FormData(event.currentTarget),image=form.get("coverFile") as File;let coverPath=selected?.coverPath||null;if(image?.size)coverPath=(await upload(image)).path;const typed=newTag.trim(),resolved=allTags.find(tag=>tag.localeCompare(typed,"fr",{sensitivity:"base"})===0)||typed;const tags=resolved&&!editingTags.includes(resolved)?[...editingTags,resolved]:editingTags;const body={name:String(form.get("name")||"").trim(),coverPath,minPlayers:Number(form.get("min")),maxPlayers:Number(form.get("max")),estimatedMinutes:Number(form.get("minutes"))||null,difficulty:Number(form.get("difficulty"))||null,rating:Number(form.get("rating"))||null,notes:String(form.get("notes")||"")||null,rulesUrl:String(form.get("rulesUrl")||"")||null,tags};const game=await json<Game>(editor==="edit"?`/api/games/${selected!.id}`:"/api/games",send(body,editor==="edit"?"PATCH":"POST"));await refresh();if(editor==="edit")setSelected({...game,playedCount:selected?.playedCount||0,avgDuration:selected?.avgDuration||null});setEditor(null);setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const removeGame=async()=>{if(!selected||!confirm(`Retirer « ${selected.name} » de la ludothèque ? Ses anciennes parties restent conservées.`))return;try{const response=await fetch(`/api/games/${selected.id}`,{method:"DELETE"});if(!response.ok)throw new Error("Impossible de retirer ce jeu.");setSelected(null);setEditor(null);setTab("games");await refresh()}catch(reason){setError((reason as Error).message)}};
  const addRule=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;setBusy(true);try{const form=new FormData(event.currentTarget);await json("/api/rules",send({gameId:selected.id,title:form.get("title"),content:form.get("content")}));setAddingRule(false);setRuleQuery("");setRules(await json<Rules>(`/api/rules?gameId=${selected.id}`));setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const addPdf=async(file:File)=>{if(!selected)return;setBusy(true);try{const uploaded=await upload(file);await json("/api/rules/pdf",send({gameId:selected.id,path:uploaded.path,fileName:uploaded.name}));setRules(await json<Rules>(`/api/rules?gameId=${selected.id}`));setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const indexExternalPdf=async()=>{if(!selected?.rulesUrl)return;setBusy(true);try{const indexed=await json<{pages:number;alreadyIndexed?:boolean}>("/api/rules/external",send({gameId:selected.id,url:selected.rulesUrl}));setRules(await json<Rules>(`/api/rules?gameId=${selected.id}`));setError(indexed.alreadyIndexed?"Ce PDF est déjà prêt pour la recherche.":`${indexed.pages} page${indexed.pages===1?"":"s"} indexée${indexed.pages===1?"":"s"}.`)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const results=ruleQuery?rules.results:rules.sections;
  const selectedDifficulty=selected?difficultyValue(selected):0;

  return <main className={`page${selected?" detail-page":""}`}>
    {error&&<div className="error" role="alert">{error}<button onClick={()=>setError("")} aria-label="Fermer"><X size={18}/></button></div>}
    {!selected&&session&&games.some(game=>game.id===session.gameId)&&<button className="active-play" onClick={()=>open(games.find(game=>game.id===session.gameId)!)}>Partie à terminer · {session.startedAt?elapsed(Math.floor((now-session.startedAt)/1000)):"sans chrono"} · Reprendre</button>}

    {selected?<>
      <div className="detail-top"><button onClick={()=>setSelected(null)}><ChevronLeft/> Retour</button><button onClick={()=>openEditor("edit")} aria-label="Modifier ce jeu"><PenLine/></button></div>
      <Cover game={selected} large/><h1 className="game-title">{selected.name}</h1>
      <div className="facts">
        <span><Users/>{selected.minPlayers} à {selected.maxPlayers} joueurs</span>
        {selected.estimatedMinutes&&<span><Clock3/>~ {selected.estimatedMinutes} min<small>estimées</small></span>}
        {selected.avgDuration&&<span><Clock3/>{selected.avgDuration} min<small>en moyenne</small></span>}
        {!!selectedDifficulty&&<span><ChartNoAxesColumnIncreasing/>{formatNumber(selectedDifficulty)}/5<small>{difficultyLabel(selectedDifficulty)}</small></span>}
      </div>
      <div className="game-meta">{selected.rating&&<span>Notre note : {selected.rating}/5</span>}<span>Joué {selected.playedCount||0} fois</span></div>{selected.tags.length>0&&<div className="game-tags">{selected.tags.map(tag=><span key={tag}>{tag}</span>)}</div>}
      {session?.gameId===selected.id?<div className="running"><small>{session.startedAt?"Partie en cours":"Partie sans chrono"}</small>{session.startedAt&&<strong aria-live="off">{elapsed(Math.floor((now-session.startedAt)/1000))}</strong>}<button className="primary" onClick={()=>setFinishing(true)}>Terminer la partie</button><button className="text-action danger" onClick={cancelPlay}>Annuler cette partie</button></div>:<button className="primary" onClick={()=>{setChosen([]);setPlayerSearch("");setPicker(true)}}>Nouvelle partie</button>}
      {gameStats&&gameStats.total>0&&<section className="game-stats"><h2>Nos parties</h2><p>{plural(gameStats.total,"partie")} enregistrée{gameStats.total===1?"":"s"}</p>{gameStats.averageScore.count>0&&<><h3>Scores</h3><p>Score moyen : <b>{formatNumber(gameStats.averageScore.value!)}</b></p>{gameStats.scoresByPlayerCount.map(row=><div className="stat-row" key={row.playerCount}><b>À {plural(row.playerCount,"joueur")}</b><span>{formatNumber(row.averageScore)} en moyenne</span></div>)}</>}<h3>Joueurs</h3>{gameStats.players.map(player=><div className="stat-row" key={player.id}><b>{player.name}</b><span>{plural(player.plays,"partie")} · {plural(player.wins,"victoire")}{player.scoreCount?` · score moyen ${formatNumber(player.averageScore!)}`:""}</span></div>)}</section>}
      <section className="rules" id="rules"><h2>Règles</h2>{selected.rulesUrl&&<a className="rules-link" href={selected.rulesUrl} target="_blank" rel="noopener noreferrer"><BookOpen/> Consulter les règles</a>}{selected.rulesUrl?.split("?")[0].toLowerCase().endsWith(".pdf")&&!hasIndexedExternalPdf&&<button className="text-action" disabled={busy} onClick={indexExternalPdf}>+ Rendre ce PDF recherchable</button>}{rules.documents.map(document=><a className="rules-link" key={document.id} href={document.filePath} target="_blank" rel="noopener noreferrer"><BookOpen/> {document.fileName}</a>)}<label className="search-field"><Search size={20}/><input value={ruleQuery} onChange={event=>setRuleQuery(event.target.value)} placeholder="Chercher un passage…" aria-label="Rechercher dans les règles"/></label>{results.map(rule=><article className="rule-result" key={`${rule.type||"section"}-${rule.id}`}><h3>{rule.type==="pdf"?`${rule.title} · page ${rule.page}`:rule.title}</h3><p>{ruleQuery?<Highlight text={rule.content} query={ruleQuery}/>:rule.content}</p>{rule.filePath&&<a href={`${rule.filePath}#page=${rule.page}`} target="_blank" rel="noopener noreferrer">Ouvrir la page {rule.page}</a>}</article>)}{!results.length&&<p className="muted">{ruleQuery?"Aucun passage trouvé.":rules.documents.length||rules.sections.length?"Saisissez quelques mots pour rechercher dans ces règles.":"Ajoutez un PDF ou une section pour pouvoir rechercher un passage. Les liens d’éditeur s’ouvrent directement, mais leur texte n’est pas copié sur le serveur."}</p>}<button className="text-action" onClick={()=>setAddingRule(true)}>+ Ajouter une section</button><label className="text-action file-action">+ Ajouter un PDF<input type="file" accept="application/pdf" onChange={event=>{const file=event.target.files?.[0];if(file)addPdf(file);event.target.value=""}}/></label></section>
    </>:<>
      {tab==="play"&&<><header className="hero"><Dices size={25}/><h1>À quoi on joue ?</h1></header><section className="chooser"><p>On est combien ?</p><div className="count-picker" role="group" aria-label="Nombre de joueurs">{[2,3,4,5,6,7,8].map(value=><button key={value} aria-pressed={count===value} className={count===value?"chosen":""} onClick={()=>setCount(value)}>{value===8?"8+":value}</button>)}</div><p>Combien de temps ? <span>(facultatif)</span></p><div className="duration-picker" role="group" aria-label="Durée">{[[30,"< 30 min"],[60,"30 à 60 min"],[90,"> 60 min"],[null,"Peu importe"]].map(([value,label])=><button key={label as string} aria-pressed={duration===value} className={duration===value?"chosen":""} onClick={()=>setDuration(value as number|null)}>{label}</button>)}</div><label className="filter-select">Difficulté <span>(facultatif)</span><select value={difficulty} onChange={event=>setDifficulty(event.target.value as DifficultyFilter)}>{difficultyOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{allTags.length>0&&<fieldset className="tag-filter"><legend>Types de jeu <span>(facultatif)</span></legend><div>{allTags.map(tag=>{const mode=tagFilters[tag];return <button type="button" key={tag} data-mode={mode||"neutral"} aria-label={`${tag}, ${mode==="include"?"inclus":mode==="exclude"?"exclu":"sans filtre"}`} onClick={()=>cycleTag(tag)}>{mode==="include"?"+ ":mode==="exclude"?"− ":""}{tag}</button>})}</div><small>1 appui pour inclure, 2 pour exclure, 3 pour enlever le filtre.</small></fieldset>}<button className="primary" onClick={pick}>Choisir un jeu <Dices size={20}/></button></section>{picked&&<section className="result" key={picked.id}><Cover game={picked} large/><h2>{picked.name}</h2><p>{picked.minPlayers} à {picked.maxPlayers} joueurs{picked.estimatedMinutes?` · ~ ${picked.estimatedMinutes} min`:""}{picked.avgDuration?` · ${picked.avgDuration} min chez nous`:""}</p><button className="primary" onClick={()=>open(picked)}>Jouer</button><button className="text-action" onClick={pick}>Un autre</button></section>}{!games.length&&<p className="muted">Chargement de la ludothèque…</p>}{games.length>0&&!compatible.length&&<p className="muted">Aucun jeu ne correspond à ce choix.</p>}</>}
      {tab==="games"&&<><header className="list-top"><h1>Nos jeux <small>({games.length})</small></h1><div><button onClick={()=>setSearchOpen(!searchOpen)} aria-label="Rechercher ou filtrer les jeux"><Search/></button><button onClick={()=>openEditor("new")} aria-label="Ajouter un jeu"><Plus/></button></div></header>{searchOpen&&<div className="library-filters"><label className="search-field"><Search size={20}/><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} placeholder="Chercher un jeu…"/></label><label className="filter-select">Difficulté<select value={libraryDifficulty} onChange={event=>setLibraryDifficulty(event.target.value as DifficultyFilter)}>{difficultyOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>}<div className="game-grid">{visibleGames.map(game=><button key={game.id} className="game-tile" onClick={()=>open(game)}><Cover game={game}/><span>{game.name}</span>{game.tags.length>0&&<small className="game-tile-tags">{game.tags.join(" · ")}</small>}</button>)}</div>{!visibleGames.length&&<p className="muted">Aucun jeu ne correspond à ces filtres.</p>}</>}
      {tab==="stats"&&<section className="stats"><h1>Stats</h1><strong>{plural(stats?.total||0,"partie")} jouée{stats?.total===1?"":"s"}</strong><p>{plural(stats?.totalWins||0,"victoire")} enregistrée{stats?.totalWins===1?"":"s"}</p>{stats&&stats.topGames.length>0&&<><h2>Jeux les plus joués</h2>{stats.topGames.map(game=><div className="stat-row" key={game.name}><b>{game.name}</b><span>{plural(game.plays,"partie")}</span></div>)}</>}<h2>Les joueurs</h2>{stats?.players.map(player=><div className="stat-row" key={player.id}><b>{player.name}</b><span>{plural(player.plays,"partie")} · {plural(player.wins,"victoire")}{player.plays?` · ${player.winRate||0} % de victoires`:""}</span></div>)}</section>}
      <nav className="bottom-nav" aria-label="Navigation principale"><button aria-current={tab==="play"?"page":undefined} className={tab==="play"?"active":""} onClick={()=>setTab("play")}><Dices/>Jouer</button><button aria-current={tab==="games"?"page":undefined} className={tab==="games"?"active":""} onClick={()=>setTab("games")}><LibraryBig/>Nos jeux</button><button aria-current={tab==="stats"?"page":undefined} className={tab==="stats"?"active":""} onClick={()=>setTab("stats")}><ChartNoAxesColumnIncreasing/>Stats</button></nav>
    </>}

    {picker&&<div className="sheet-backdrop" onClick={()=>setPicker(false)}><div className="sheet player-sheet" role="dialog" aria-modal="true" aria-labelledby="picker-title" onClick={event=>event.stopPropagation()}><button className="sheet-close" onClick={()=>setPicker(false)} aria-label="Fermer"><X/></button><h2 id="picker-title">Qui joue ?</h2>{chosen.length>0&&<div className="selected-players" aria-label="Participants choisis">{chosen.map(id=><button key={id} onClick={()=>setChosen(current=>current.filter(item=>item!==id))}>{players.find(player=>player.id===id)?.name}<X/></button>)}</div>}<label className="search-field player-search"><Search/><input value={playerSearch} onChange={event=>setPlayerSearch(event.target.value)} placeholder="Chercher un joueur connu…" aria-label="Chercher un joueur connu"/></label><div className="known-player-list">{availablePlayers.map(player=><button key={player.id} onClick={()=>{setChosen(current=>[...current,player.id]);setPlayerSearch("")}}><span>{player.name}</span><Plus/></button>)}</div>{players.length>0&&!availablePlayers.length&&<p className="muted player-empty">Aucun autre joueur trouvé.</p>}<form className="add-player" onSubmit={addPlayer}><input value={newPlayer} onChange={event=>setNewPlayer(event.target.value)} placeholder="Ajouter un nouveau prénom" aria-label="Nouveau joueur"/><button type="submit" aria-label="Ajouter le joueur"><Plus/></button></form><button className="primary" disabled={!chosen.length} onClick={start}>Commencer avec le chrono</button><button className="text-action" disabled={!chosen.length} onClick={recordFinished}>Noter une partie déjà terminée</button></div></div>}

    {finishing&&session&&<div className="sheet-backdrop" onClick={()=>setFinishing(false)}><div className="sheet" role="dialog" aria-modal="true" aria-labelledby="winner-title" onClick={event=>event.stopPropagation()}><button className="sheet-close" onClick={()=>setFinishing(false)} aria-label="Fermer"><X/></button><h2 id="winner-title">Qui a gagné ?</h2><p className="finished-time">Durée : {session.startedAt?elapsed(Math.floor((now-session.startedAt)/1000)):"non enregistrée"}</p>{session.startedAt&&<button className="text-action" onClick={()=>setSession({...session,startedAt:null})}>Ne pas enregistrer ce chrono</button>}<div className="player-grid">{session.players.map(id=>{const player=players.find(item=>item.id===id);return <button key={id} aria-pressed={winners.includes(id)} className={winners.includes(id)?"chosen":""} onClick={()=>setWinners(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])}>{player?.name||"Joueur"}</button>})}</div><p className="muted">Plusieurs gagnants possibles. Aucun si tout le monde a perdu.</p><fieldset className="scores"><legend>Scores <span>(facultatifs)</span></legend>{session.players.map(id=><label key={id}><span>{players.find(player=>player.id===id)?.name||"Joueur"}</span><input type="number" step="any" inputMode="decimal" value={scores[id]||""} onChange={event=>setScores(current=>({...current,[id]:event.target.value}))} placeholder="Score" aria-label={`Score de ${players.find(player=>player.id===id)?.name||"Joueur"}`}/></label>)}</fieldset><button className="primary" disabled={busy} onClick={savePlay}>Enregistrer la partie</button></div></div>}

    {replayPrompt&&lastPlay&&<div className="sheet-backdrop"><div className="sheet replay-sheet" role="dialog" aria-modal="true" aria-labelledby="replay-title"><h2 id="replay-title">Partie enregistrée</h2><p>Vous en refaites une avec les mêmes joueurs ?</p><button className="primary" onClick={replay}>Rejouer</button><button className="text-action" onClick={()=>setReplayPrompt(false)}>Terminé</button></div></div>}

    {editor&&<div className="sheet-backdrop" onClick={()=>setEditor(null)}><form className="sheet form-sheet" role="dialog" aria-modal="true" aria-labelledby="editor-title" onClick={event=>event.stopPropagation()} onSubmit={saveGame}>
      <button type="button" className="sheet-close" onClick={()=>setEditor(null)} aria-label="Fermer"><X/></button><h2 id="editor-title">{editor==="new"?"Ajouter un jeu":"Modifier le jeu"}</h2>
      <label>Nom<input name="name" required defaultValue={editor==="edit"?selected?.name:""}/></label><label>Photo de la boîte<input name="coverFile" type="file" accept="image/jpeg,image/png,image/webp"/></label>
      <div className="two-fields"><label>Joueurs min<input name="min" type="number" min="1" required defaultValue={editor==="edit"?selected?.minPlayers:2}/></label><label>Joueurs max<input name="max" type="number" min="1" required defaultValue={editor==="edit"?selected?.maxPlayers:4}/></label></div>
      <label>Durée approximative (min)<input name="minutes" type="number" min="1" defaultValue={editor==="edit"?selected?.estimatedMinutes||"":""}/></label><label>Difficulté / 5<input name="difficulty" type="number" min="1" max="5" step="0.01" defaultValue={editor==="edit"?selected?.difficulty||"":""}/></label><label>Notre note / 5<input name="rating" type="number" min="1" max="5" defaultValue={editor==="edit"?selected?.rating||"":""}/></label>
      <fieldset className="editor-tags"><legend>Tags</legend><div className="editor-tag-list">{editorTagChoices.map(tag=><button type="button" key={tag} aria-pressed={editingTags.includes(tag)} className={editingTags.includes(tag)?"chosen":""} onClick={()=>toggleEditingTag(tag)}>{editingTags.includes(tag)?"✓ ":""}{tag}</button>)}</div><label>Nouveau tag<div className="new-tag"><input value={newTag} onChange={event=>setNewTag(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();addEditingTag()}}} placeholder="Ex. Jeu coopératif"/><button type="button" onClick={addEditingTag} disabled={!newTag.trim()} aria-label="Ajouter ce tag"><Plus/></button></div></label></fieldset>
      <label>Lien des règles<input name="rulesUrl" type="url" defaultValue={editor==="edit"?selected?.rulesUrl||"":""} placeholder="https://…"/></label><label>Notes<textarea name="notes" rows={2} defaultValue={editor==="edit"?selected?.notes||"":""}/></label><button className="primary" disabled={busy}>{editor==="new"?"Ajouter le jeu":"Enregistrer"}</button>{editor==="edit"&&<button type="button" className="remove-game" onClick={removeGame}><Trash2 size={18}/> Retirer ce jeu</button>}
    </form></div>}

    {addingRule&&<div className="sheet-backdrop" onClick={()=>setAddingRule(false)}><form className="sheet form-sheet" role="dialog" aria-modal="true" aria-labelledby="rule-title" onClick={event=>event.stopPropagation()} onSubmit={addRule}><button type="button" className="sheet-close" onClick={()=>setAddingRule(false)} aria-label="Fermer"><X/></button><h2 id="rule-title">Ajouter une règle</h2><label>Section<input name="title" required placeholder="Mise en place, échanges…"/></label><label>Texte<textarea name="content" required rows={8}/></label><button className="primary" disabled={busy}>Enregistrer</button></form></div>}
  </main>;
}

function Highlight({text,query}:{text:string;query:string}) {const term=query.trim().split(/\s+/)[0];if(!term)return text;const index=text.toLocaleLowerCase("fr").indexOf(term.toLocaleLowerCase("fr"));if(index<0)return text.length>360?`${text.slice(0,360)}…`:text;const from=Math.max(0,index-100),to=Math.min(text.length,index+term.length+220);return <>{from>0&&"…"}{text.slice(from,index)}<mark>{text.slice(index,index+term.length)}</mark>{text.slice(index+term.length,to)}{to<text.length&&"…"}</>}
