"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, ChartNoAxesColumnIncreasing, ChevronLeft, Clock3, Dices, LibraryBig, PenLine, Plus, Search, Trash2, Users, X } from "lucide-react";

type Game = { id:number; name:string; coverPath:string|null; minPlayers:number; maxPlayers:number; estimatedMinutes:number|null; avgDuration:number|null; difficulty:string|number|null; rating:number|null; notes:string|null; rulesUrl:string|null; lowerScoreWins:boolean; tags:string[]; playedCount:number };
type Player = { id:number; name:string };
type Session = { gameId:number; players:number[]; startedAt:number|null; elapsedSeconds:number; tracking:boolean; paused:boolean; events:{eventId:number;playerId:number}[]; version:number };
type DifficultyFilter = "veryEasy"|"easy"|"medium"|"complex"|"hard";
type DurationFilter = "short"|"medium"|"long";
type LibrarySort = "name"|"difficulty"|"time"|"players";
type TagMode = "include"|"exclude";
type Rule = { id:number; title:string; content:string; type?:"section"|"pdf"; page?:number; filePath?:string };
type Rules = { sections:Rule[]; documents:{id:number;fileName:string;filePath:string}[]; results:Rule[] };
type Stats = {
  total:number;
  totalWins:number;
  totalDuration:{value:number};
  averageDuration:{value:number|null;count:number};
  topGames:{name:string;plays:number}[];
  players:{id:number;name:string;plays:number;wins:number;winRate:number|null;totalDuration:number}[];
};
type GameEvent={id:number;name:string;total:number};
type PlayerStats = { player:Player; total:number; wins:number; winRate:{value:number|null}; totalDuration:{value:number}; averageDuration:{value:number|null;count:number}; averageScore:{value:number|null;count:number}; games:{id:number;name:string;plays:number;wins:number;winRate:number|null;totalDuration:number;averageDuration:number|null;averageScore:number|null;scoreCount:number}[] };
type HistoryPlay={id:number;gameId:number;gameName:string;playedAt:string;duration:number|null;notes:string|null;participants:{id:number;name:string;winner:number;score:number|null}[];events:{id:number;name:string;count:number;playerName?:string|null}[]};
type GameStats = {
  total:number;
  averageDuration:{value:number|null;count:number};
  totalDuration:{value:number};
  durationByPlayerCount:{playerCount:number;averageDuration:number;count:number}[];
  averageScore:{value:number|null;count:number};
  bestScore:{value:number;playerId:number;playerName:string}|null;
  bestMonthlyScore:{value:number;playerId:number;playerName:string}|null;
  lowestScore:{value:number;playerId:number;playerName:string}|null;
  lowestMonthlyScore:{value:number;playerId:number;playerName:string}|null;
  scoresByPlayerCount:{playerCount:number;averageScore:number;scoreCount:number}[];
  players:{id:number;name:string;plays:number;wins:number;averageScore:number|null;scoreCount:number;totalDuration:number}[];
};

const blankRules:Rules={sections:[],documents:[],results:[]};
const difficultyOptions:[DifficultyFilter,string][]=[["veryEasy","Très facile"],["easy","Facile"],["medium","Intermédiaire"],["complex","Complexe"],["hard","Exigeant"]];
const durationOptions:[DurationFilter,string][]=[["short","< 30 min"],["medium","30 à 60 min"],["long","> 60 min"]];
const json=async<T,>(url:string,options?:RequestInit):Promise<T>=>{const response=await fetch(url,options);const body=await response.json();if(!response.ok)throw new Error(body.error||"Une erreur est survenue.");return body as T};
const send=(body:unknown,method="POST"):RequestInit=>({method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
const elapsed=(seconds:number)=>{const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return [h,m,s].map(value=>String(value).padStart(2,"0")).join(":")};
const difficultyValue=(game:Game)=>Number(game.difficulty)||0;
const difficultyLabel=(value:number)=>value<1?"Très facile":value<2?"Facile":value<3?"Intermédiaire":value<4?"Complexe":"Exigeant";
const difficultyBand=(value:number):DifficultyFilter=>value<1?"veryEasy":value<2?"easy":value<3?"medium":value<4?"complex":"hard";
const matchesDifficulty=(game:Game,filters:DifficultyFilter[])=>!filters.length||(game.difficulty!==null&&game.difficulty!==""&&filters.includes(difficultyBand(difficultyValue(game))));
const matchesDuration=(game:Game,filters:DurationFilter[])=>!filters.length||(game.estimatedMinutes!==null&&filters.includes(game.estimatedMinutes<30?"short":game.estimatedMinutes<=60?"medium":"long"));
const matchesTags=(game:Game,filters:Record<string,TagMode>)=>{const included=Object.keys(filters).filter(tag=>filters[tag]==="include"),excluded=Object.keys(filters).filter(tag=>filters[tag]==="exclude");return(!included.length||included.some(tag=>game.tags.includes(tag)))&&!excluded.some(tag=>game.tags.includes(tag))};
const formatNumber=(value:number)=>value.toLocaleString("fr-FR",{maximumFractionDigits:2});
const formatDuration=(minutes:number)=>{const total=Math.max(0,Math.round(minutes)),days=Math.floor(total/1440),hours=Math.floor(total%1440/60),remaining=total%60,parts:string[]=[];if(days)parts.push(`${days} j`);if(hours)parts.push(`${hours} h`);if(remaining||!parts.length)parts.push(`${remaining} min`);return parts.join(" ")};
const plural=(count:number,word:string)=>`${count} ${word}${count===1?"":"s"}`;
const compressCover=async(file:File):Promise<File>=>{if(!file.type.startsWith("image/"))return file;const image=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext("2d");if(!context){image.close();return file}context.drawImage(image,0,0,canvas.width,canvas.height);image.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.82));return blob&&blob.size<file.size?new File([blob],"cover.jpg",{type:"image/jpeg"}):file};

function Cover({game,large=false}:{game:Game;large?:boolean}) {
  const [failed,setFailed]=useState(false);
  useEffect(()=>setFailed(false),[game.coverPath]);
  return <div className={`cover${large?" cover-large":""}${game.coverPath&&!failed?" has-image":""}`} aria-label={`Boîte de ${game.name}`} role="img">
    {game.coverPath&&!failed?<img src={game.coverPath} alt="" loading={large?"eager":"lazy"} decoding="async" fetchPriority={large?"high":"low"} onError={()=>setFailed(true)}/>:<span>{game.name}</span>}
  </div>;
}

export default function FamilyApp() {
  const [tab,setTab]=useState<"play"|"games"|"stats"|"history">("play");
  const [games,setGames]=useState<Game[]>([]),[players,setPlayers]=useState<Player[]>([]),[selected,setSelected]=useState<Game|null>(null);
  const [count,setCount]=useState(4),[duration,setDuration]=useState<DurationFilter[]>([]),[difficulty,setDifficulty]=useState<DifficultyFilter[]>([]),[picked,setPicked]=useState<Game|null>(null);
  const [tagFilters,setTagFilters]=useState<Record<string,TagMode>>({});
  const [editingTags,setEditingTags]=useState<string[]>([]),[newTag,setNewTag]=useState("");
  const [searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState(""),[libraryDifficulty,setLibraryDifficulty]=useState<DifficultyFilter[]>([]),[libraryDuration,setLibraryDuration]=useState<DurationFilter[]>([]),[libraryPlayers,setLibraryPlayers]=useState<number|null>(null),[librarySort,setLibrarySort]=useState<LibrarySort>("name"),[editingDifficulty,setEditingDifficulty]=useState(2),[editor,setEditor]=useState<"new"|"edit"|null>(null);
  const [picker,setPicker]=useState(false),[finishing,setFinishing]=useState(false),[replayPrompt,setReplayPrompt]=useState(false),[chosen,setChosen]=useState<number[]>([]),[winners,setWinners]=useState<number[]>([]),[scores,setScores]=useState<Record<number,string>>({}),[newPlayer,setNewPlayer]=useState(""),[playerSearch,setPlayerSearch]=useState("");
  const [session,setSession]=useState<Session|null>(null),[lastPlay,setLastPlay]=useState<Session|null>(null),[now,setNow]=useState(Date.now());
  const [rules,setRules]=useState<Rules>(blankRules),[ruleQuery,setRuleQuery]=useState(""),[debouncedRuleQuery,setDebouncedRuleQuery]=useState(""),[addingRule,setAddingRule]=useState(false),[stats,setStats]=useState<Stats|null>(null),[selectedStatsPlayer,setSelectedStatsPlayer]=useState<number|null>(null),[playerStats,setPlayerStats]=useState<PlayerStats|null>(null),[gameStats,setGameStats]=useState<GameStats|null>(null),[history,setHistory]=useState<HistoryPlay[]>([]),[editingHistory,setEditingHistory]=useState<HistoryPlay|null>(null),[historyPlayers,setHistoryPlayers]=useState<number[]>([]),[gameEvents,setGameEvents]=useState<GameEvent[]>([]),[eventName,setEventName]=useState("");
  const [busy,setBusy]=useState(false),[error,setError]=useState("");

  const refresh=async()=>{const [nextGames,nextPlayers]=await Promise.all([json<Game[]>("/api/games"),json<Player[]>("/api/players")]);setGames(nextGames);setPlayers(nextPlayers);setSelected(current=>current?nextGames.find(game=>game.id===current.id)||null:null)};
  useEffect(()=>{refresh().catch(reason=>setError(reason.message));json<Session|null>("/api/session").then(setSession).catch(reason=>setError(reason.message));if("serviceWorker" in navigator){navigator.serviceWorker.register("/sw.js",{updateViaCache:"none"}).then(registration=>registration.update()).catch(()=>{});let reloaded=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!reloaded){reloaded=true;window.location.reload()}})}},[]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{const timer=window.setInterval(()=>json<Session|null>("/api/session").then(remote=>setSession(current=>remote===null?null:(!current||remote.version>current.version)?remote:current)).catch(()=>{}),3000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedRuleQuery(ruleQuery),250);return()=>window.clearTimeout(timer)},[ruleQuery]);
  useEffect(()=>{if(!selected)return;json<Rules>(`/api/rules?gameId=${selected.id}${debouncedRuleQuery?`&q=${encodeURIComponent(debouncedRuleQuery)}`:""}`).then(setRules).catch(reason=>setError(reason.message))},[selected,debouncedRuleQuery]);
  useEffect(()=>{if(!selected){setGameEvents([]);return}json<GameEvent[]>(`/api/events?gameId=${selected.id}`).then(setGameEvents).catch(reason=>setError(reason.message))},[selected?.id]);
  useEffect(()=>{if(!selected)return;json<GameStats>(`/api/stats?gameId=${selected.id}`).then(setGameStats).catch(reason=>setError(reason.message))},[selected?.id,selected?.playedCount]);
  useEffect(()=>{if(tab==="stats")json<Stats>("/api/stats").then(setStats).catch(reason=>setError(reason.message))},[tab]);
  useEffect(()=>{if(tab!=="stats"||selectedStatsPlayer===null){setPlayerStats(null);return}json<PlayerStats>(`/api/stats?playerId=${selectedStatsPlayer}`).then(setPlayerStats).catch(reason=>setError(reason.message))},[tab,selectedStatsPlayer]);
  useEffect(()=>{if(tab==="history")json<HistoryPlay[]>("/api/history").then(setHistory).catch(reason=>setError(reason.message))},[tab]);

  const allTags=useMemo(()=>[...new Set(games.flatMap(game=>game.tags))].sort((a,b)=>a.localeCompare(b,"fr")),[games]);
  const editorTagChoices=useMemo(()=>[...new Set([...allTags,...editingTags])],[allTags,editingTags]);
  const compatible=useMemo(()=>games.filter(game=>game.minPlayers<=count&&game.maxPlayers>=count&&matchesDifficulty(game,difficulty)&&matchesTags(game,tagFilters)&&matchesDuration(game,duration)),[games,count,duration,difficulty,tagFilters]);
  const visibleGames=useMemo(()=>games.filter(game=>game.name.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr"))&&matchesDifficulty(game,libraryDifficulty)&&matchesDuration(game,libraryDuration)&&(libraryPlayers===null||(game.minPlayers<=libraryPlayers&&game.maxPlayers>=libraryPlayers))).sort((a,b)=>librarySort==="name"?a.name.localeCompare(b.name,"fr"):librarySort==="difficulty"?difficultyValue(a)-difficultyValue(b):librarySort==="time"?(a.estimatedMinutes??Infinity)-(b.estimatedMinutes??Infinity):a.minPlayers-b.minPlayers||a.maxPlayers-b.maxPlayers||a.name.localeCompare(b.name,"fr")),[games,search,libraryDifficulty,libraryDuration,libraryPlayers,librarySort]);
  const availablePlayers=useMemo(()=>players.filter(player=>!chosen.includes(player.id)&&player.name.toLocaleLowerCase("fr").includes(playerSearch.trim().toLocaleLowerCase("fr"))),[players,chosen,playerSearch]);
  const hasIndexedExternalPdf=!!selected?.rulesUrl&&rules.documents.some(document=>document.filePath===selected.rulesUrl);
  const pick=()=>setPicked(compatible[Math.floor(Math.random()*compatible.length)]||null);
  const cycleTag=(tag:string)=>setTagFilters(current=>{const next={...current};if(!next[tag])next[tag]="include";else if(next[tag]==="include")next[tag]="exclude";else delete next[tag];return next});
  const openEditor=(mode:"new"|"edit")=>{setEditingTags(mode==="edit"?selected?.tags||[]:[]);setEditingDifficulty(mode==="edit"&&selected&&selected.difficulty!==null?difficultyValue(selected):2);setNewTag("");setEditor(mode)};
  const toggleDifficulty=(value:DifficultyFilter)=>setDifficulty(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);
  const toggleDuration=(value:DurationFilter)=>setDuration(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);
  const toggleLibraryDifficulty=(value:DifficultyFilter)=>setLibraryDifficulty(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);
  const toggleLibraryDuration=(value:DurationFilter)=>setLibraryDuration(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);
  const toggleEditingTag=(tag:string)=>setEditingTags(current=>current.includes(tag)?current.filter(item=>item!==tag):[...current,tag]);
  const addEditingTag=()=>{const value=newTag.trim(),tag=allTags.find(item=>item.localeCompare(value,"fr",{sensitivity:"base"})===0)||value;if(tag)setEditingTags(current=>current.includes(tag)?current:[...current,tag]);setNewTag("")};
  const open=(game:Game)=>{setSelected(game);setGameStats(null);setRuleQuery("");setDebouncedRuleQuery("");setError("")};
  const secondsIn=(value:Session)=>value.startedAt&&!value.paused?value.elapsedSeconds+Math.max(0,Math.floor((Date.now()-value.startedAt)/1000)):value.elapsedSeconds;
  const updateSession=async(next:Omit<Session,"version">)=>{const response=await fetch("/api/session",send({...next,expectedVersion:session?.version||0},"PUT")),body=await response.json();if(!response.ok){if("session" in body)setSession(body.session);throw new Error(body.error||"Conflit de synchronisation.")}setSession(body);return body as Session};
  const clearSession=async()=>{if(!session)return;const response=await fetch(`/api/session?expectedVersion=${session.version}`,{method:"DELETE"});if(response.status===409){const body=await response.json();setSession(body.session??null);throw new Error(body.error)}if(!response.ok)throw new Error("Impossible de synchroniser la fin de partie.");setSession(null);setFinishing(false);setWinners([]);setScores({})};
  const cancelPlay=async()=>{if(confirm("Annuler cette partie et son chrono ?"))try{await clearSession()}catch(reason){setError((reason as Error).message)}};
  const pauseToggle=async()=>{if(!session)return;try{const elapsedSeconds=secondsIn(session);await updateSession({...session,elapsedSeconds,startedAt:session.paused?Date.now():session.startedAt,paused:!session.paused});setNow(Date.now())}catch(reason){setError((reason as Error).message)}};
  const recordEvent=async(eventId:number,playerId:number)=>{if(!session)return;try{await updateSession({...session,elapsedSeconds:secondsIn(session),events:[...session.events,{eventId,playerId}]})}catch(reason){setError((reason as Error).message)}};

  const addPlayer=async(event:React.FormEvent)=>{event.preventDefault();if(!newPlayer.trim())return;try{const player=await json<Player>("/api/players",send({name:newPlayer.trim()}));setPlayers(current=>[...current,player].sort((a,b)=>a.name.localeCompare(b.name,"fr")));setChosen(current=>[...current,player.id]);setNewPlayer("");setPlayerSearch("");setError("")}catch(reason){setError((reason as Error).message)}};
  const start=async()=>{if(!selected||!chosen.length)return;try{await updateSession({gameId:selected.id,players:chosen,startedAt:Date.now(),elapsedSeconds:0,tracking:true,paused:false,events:[]});setPicker(false);setFinishing(false);setNow(Date.now())}catch(reason){setError((reason as Error).message)}};
  const recordFinished=async()=>{if(!selected||!chosen.length)return;try{await updateSession({gameId:selected.id,players:chosen,startedAt:null,elapsedSeconds:0,tracking:false,paused:true,events:[]});setPicker(false);setFinishing(true)}catch(reason){setError((reason as Error).message)}};
  const savePlay=async()=>{if(!session||busy)return;setBusy(true);try{const participants=session.players.map(id=>{const raw=scores[id]?.trim();return{id,winner:winners.includes(id),...(raw?{score:Number(raw)}:{})}}),events=session.events.map(event=>({id:event.eventId,playerId:event.playerId,count:1}));await clearSession();await json("/api/plays",send({gameId:session.gameId,duration:session.tracking?Math.max(1,Math.round(secondsIn(session)/60)):null,players:participants,events}));setLastPlay(session);setChosen([]);await refresh();setReplayPrompt(true);setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const replay=async()=>{if(!lastPlay)return;try{await updateSession({gameId:lastPlay.gameId,players:lastPlay.players,startedAt:Date.now(),elapsedSeconds:0,tracking:true,paused:false,events:[]});setChosen(lastPlay.players);setReplayPrompt(false);setNow(Date.now())}catch(reason){setError((reason as Error).message)}};

  const upload=async(file:File)=>{let uploadFile=file;try{uploadFile=await compressCover(file)}catch{}const form=new FormData();form.append("file",uploadFile);return json<{path:string;name:string}>("/api/media",{method:"POST",body:form})};
  const saveGame=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);try{const form=new FormData(event.currentTarget),image=form.get("coverFile") as File;let coverPath=selected?.coverPath||null;if(image?.size)coverPath=(await upload(image)).path;const typed=newTag.trim(),resolved=allTags.find(tag=>tag.localeCompare(typed,"fr",{sensitivity:"base"})===0)||typed;const tags=resolved&&!editingTags.includes(resolved)?[...editingTags,resolved]:editingTags;const body={name:String(form.get("name")||"").trim(),coverPath,minPlayers:Number(form.get("min")),maxPlayers:Number(form.get("max")),estimatedMinutes:Number(form.get("minutes"))||null,difficulty:editingDifficulty,rating:Number(form.get("rating"))||null,notes:String(form.get("notes")||"")||null,rulesUrl:String(form.get("rulesUrl")||"")||null,lowerScoreWins:form.get("lowerScoreWins")==="on",tags};const game=await json<Game>(editor==="edit"?`/api/games/${selected!.id}`:"/api/games",send(body,editor==="edit"?"PATCH":"POST"));await refresh();if(editor==="edit")setSelected({...game,playedCount:selected?.playedCount||0,avgDuration:selected?.avgDuration||null});setEditor(null);setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const removeGame=async()=>{if(!selected||!confirm(`Retirer « ${selected.name} » de la ludothèque ? Ses anciennes parties restent conservées.`))return;try{const response=await fetch(`/api/games/${selected.id}`,{method:"DELETE"});if(!response.ok)throw new Error("Impossible de retirer ce jeu.");setSelected(null);setEditor(null);setTab("games");await refresh()}catch(reason){setError((reason as Error).message)}};
  const addRule=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;setBusy(true);try{const form=new FormData(event.currentTarget);await json("/api/rules",send({gameId:selected.id,title:form.get("title"),content:form.get("content")}));setAddingRule(false);setRuleQuery("");setRules(await json<Rules>(`/api/rules?gameId=${selected.id}`));setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const addGameEvent=async(event:React.FormEvent)=>{event.preventDefault();if(!selected||!eventName.trim())return;try{const created=await json<GameEvent>("/api/events",send({gameId:selected.id,name:eventName}));setGameEvents(current=>[...current,created].sort((a,b)=>a.name.localeCompare(b.name,"fr")));setEventName("")}catch(reason){setError((reason as Error).message)}};
  const addPdf=async(file:File)=>{if(!selected)return;setBusy(true);try{const uploaded=await upload(file);await json("/api/rules/pdf",send({gameId:selected.id,path:uploaded.path,fileName:uploaded.name}));setRules(await json<Rules>(`/api/rules?gameId=${selected.id}`));setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const indexExternalPdf=async()=>{if(!selected?.rulesUrl)return;setBusy(true);try{const indexed=await json<{pages:number;alreadyIndexed?:boolean}>("/api/rules/external",send({gameId:selected.id,url:selected.rulesUrl}));setRules(await json<Rules>(`/api/rules?gameId=${selected.id}`));setError(indexed.alreadyIndexed?"Ce PDF est déjà prêt pour la recherche.":`${indexed.pages} page${indexed.pages===1?"":"s"} indexée${indexed.pages===1?"":"s"}.`)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const openHistoryEdit=(play:HistoryPlay)=>{setEditingHistory(play);setHistoryPlayers(play.participants.map(participant=>participant.id));setWinners(play.participants.filter(participant=>participant.winner).map(participant=>participant.id));setScores(Object.fromEntries(play.participants.filter(participant=>participant.score!==null).map(participant=>[participant.id,String(participant.score)])));};
  const saveHistory=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editingHistory||!historyPlayers.length)return;setBusy(true);try{const form=new FormData(event.currentTarget),participants=historyPlayers.map(id=>{const score=scores[id]?.trim();return{id,winner:winners.includes(id),...(score?{score:Number(score)}:{})}});await json(`/api/history/${editingHistory.id}`,send({duration:Number(form.get("duration"))||null,notes:String(form.get("notes")||""),players:participants},"PATCH"));setEditingHistory(null);setHistory(await json<HistoryPlay[]>("/api/history"));setStats(await json<Stats>("/api/stats"));setError("")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const results=ruleQuery?rules.results:rules.sections;
  const selectedDifficulty=selected?difficultyValue(selected):0;

  return <main className={`page${selected?" detail-page":""}`}>
    {error&&<div className="error" role="alert">{error}<button onClick={()=>setError("")} aria-label="Fermer"><X size={18}/></button></div>}
    {!selected&&session&&games.some(game=>game.id===session.gameId)&&<button className="active-play" onClick={()=>open(games.find(game=>game.id===session.gameId)!)}>Partie en cours sur un autre téléphone · {session.tracking?elapsed(secondsIn(session)):"sans chrono"} · Rejoindre</button>}

    {selected?<>
      <div className="detail-top"><button onClick={()=>setSelected(null)}><ChevronLeft/> Retour</button><button onClick={()=>openEditor("edit")} aria-label="Modifier ce jeu"><PenLine/></button></div>
      <Cover game={selected} large/><h1 className="game-title">{selected.name}</h1>
      <div className="facts">
        <span><Users/>{selected.minPlayers} à {selected.maxPlayers} joueurs</span>
        {selected.estimatedMinutes&&<span><Clock3/>~ {formatDuration(selected.estimatedMinutes)}<small>estimées</small></span>}
        {selected.avgDuration&&<span><Clock3/>{formatDuration(selected.avgDuration)}<small>en moyenne</small></span>}
        {!!selectedDifficulty&&<span><ChartNoAxesColumnIncreasing/>{formatNumber(selectedDifficulty)}/5<small>{difficultyLabel(selectedDifficulty)}</small></span>}
      </div>
      <div className="game-meta">{selected.rating&&<span>Notre note : {selected.rating}/5</span>}<span>Joué {selected.playedCount||0} fois</span></div>{selected.tags.length>0&&<div className="game-tags">{selected.tags.map(tag=><span key={tag}>{tag}</span>)}</div>}
      {session?.gameId===selected.id?<div className="running"><small>{session.tracking?(session.paused?"Chrono en pause":"Partie en cours"):"Partie sans chrono"}</small>{session.tracking&&<strong aria-live="off">{elapsed(secondsIn(session))}</strong>}<button className="primary" onClick={pauseToggle}>{session.paused?"Reprendre le chrono":"Mettre le chrono en pause"}</button><button className="text-action" onClick={()=>setFinishing(true)}>Terminer la partie</button>{gameEvents.length>0&&<div className="session-events">{gameEvents.map(event=><details key={event.id}><summary>+ {event.name}</summary><div>{session.players.map(id=><button key={id} onClick={()=>recordEvent(event.id,id)}>{players.find(player=>player.id===id)?.name}</button>)}</div></details>)}</div>}<button className="text-action danger" onClick={cancelPlay}>Annuler cette partie</button></div>:<button className="primary" onClick={()=>{setChosen([]);setPlayerSearch("");setPicker(true)}}>Nouvelle partie</button>}
      {gameStats&&gameStats.total>0&&<details className="game-stats" open><summary><h2>Nos parties</h2></summary><p>{plural(gameStats.total,"partie")} enregistrée{gameStats.total===1?"":"s"} · Temps joué : <b>{formatDuration(gameStats.totalDuration.value)}</b></p>{gameStats.averageDuration.count>0&&<><h3>Durées</h3><p>Durée moyenne : <b>{formatDuration(gameStats.averageDuration.value!)}</b></p>{gameStats.durationByPlayerCount.map(row=><div className="stat-row" key={row.playerCount}><b>À {plural(row.playerCount,"joueur")}</b><span>{formatDuration(row.averageDuration)} en moyenne · {plural(row.count,"partie")}</span></div>)}</>}{gameStats.averageScore.count>0&&<><h3>Scores</h3><p>Score moyen : <b>{formatNumber(gameStats.averageScore.value!)}</b></p>{gameStats.bestScore&&<p>Meilleur score : <b>{formatNumber(gameStats.bestScore.value)}</b> par <b>{gameStats.bestScore.playerName}</b></p>}{gameStats.bestMonthlyScore&&gameStats.bestMonthlyScore.value!==gameStats.bestScore?.value&&<p>Meilleur score du mois : <b>{formatNumber(gameStats.bestMonthlyScore.value)}</b> par <b>{gameStats.bestMonthlyScore.playerName}</b></p>}{gameStats.lowestScore&&<p>{selected.lowerScoreWins?"Score le moins bon":"Score minimum"} : <b>{formatNumber(gameStats.lowestScore.value)}</b> par <b>{gameStats.lowestScore.playerName}</b></p>}{gameStats.lowestMonthlyScore&&gameStats.lowestMonthlyScore.value!==gameStats.lowestScore?.value&&<p>{selected.lowerScoreWins?"Score le moins bon du mois":"Score minimum du mois"} : <b>{formatNumber(gameStats.lowestMonthlyScore.value)}</b> par <b>{gameStats.lowestMonthlyScore.playerName}</b></p>}{gameStats.scoresByPlayerCount.map(row=><div className="stat-row" key={row.playerCount}><b>À {plural(row.playerCount,"joueur")}</b><span>{formatNumber(row.averageScore)} en moyenne</span></div>)}</>}<h3>Joueurs</h3>{gameStats.players.map(player=><div className="stat-row" key={player.id}><b>{player.name}</b><span>{plural(player.plays,"partie")} · {plural(player.wins,"victoire")}{player.scoreCount?` · score moyen ${formatNumber(player.averageScore!)}`:""}</span></div>)}</details>}
      <details className="rules" open><summary><h2>Événements spéciaux</h2></summary>{gameEvents.map(event=><div className="stat-row" key={event.id}><b>{event.name}</b><span>{event.total} fois</span></div>)}<form className="add-player" onSubmit={addGameEvent}><input value={eventName} onChange={event=>setEventName(event.target.value)} maxLength={60} placeholder="Ex. Yams sec"/><button type="submit" aria-label="Ajouter l’événement"><Plus/></button></form></details>
      <details className="rules" id="rules" open><summary><h2>Règles</h2></summary>{selected.rulesUrl&&<a className="rules-link" href={selected.rulesUrl} target="_blank" rel="noopener noreferrer"><BookOpen/> Consulter les règles</a>}{selected.rulesUrl?.split("?")[0].toLowerCase().endsWith(".pdf")&&!hasIndexedExternalPdf&&<button className="text-action" disabled={busy} onClick={indexExternalPdf}>+ Rendre ce PDF recherchable</button>}{rules.documents.map(document=><a className="rules-link" key={document.id} href={document.filePath} target="_blank" rel="noopener noreferrer"><BookOpen/> {document.fileName}</a>)}<label className="search-field"><Search size={20}/><input value={ruleQuery} onChange={event=>setRuleQuery(event.target.value)} placeholder="Chercher un passage…" aria-label="Rechercher dans les règles"/></label>{results.map(rule=><article className="rule-result" key={`${rule.type||"section"}-${rule.id}`}><h3>{rule.type==="pdf"?`${rule.title} · page ${rule.page}`:rule.title}</h3><p>{ruleQuery?<Highlight text={rule.content} query={ruleQuery}/>:rule.content}</p>{rule.filePath&&<a href={`${rule.filePath}#page=${rule.page}`} target="_blank" rel="noopener noreferrer">Ouvrir la page {rule.page}</a>}</article>)}{!results.length&&<p className="muted">{ruleQuery?"Aucun passage trouvé.":rules.documents.length||rules.sections.length?"Saisissez quelques mots pour rechercher dans ces règles.":"Ajoutez un PDF ou une section pour pouvoir rechercher un passage. Les liens d’éditeur s’ouvrent directement, mais leur texte n’est pas copié sur le serveur."}</p>}<button className="text-action" onClick={()=>setAddingRule(true)}>+ Ajouter une section</button><label className="text-action file-action">+ Ajouter un PDF<input type="file" accept="application/pdf" onChange={event=>{const file=event.target.files?.[0];if(file)addPdf(file);event.target.value=""}}/></label></details>
    </>:<>
      {tab==="play"&&<><header className="hero"><img className="app-logo hero-logo" src="/icon.svg" alt=""/><h1>À quoi on joue ?</h1></header><section className="chooser"><p>On est combien ?</p><div className="count-picker" role="group" aria-label="Nombre de joueurs">{[2,3,4,5,6,7,8].map(value=><button key={value} aria-pressed={count===value} className={count===value?"chosen":""} onClick={()=>setCount(value)}>{value===8?"8+":value}</button>)}</div><fieldset className="choice-filter"><legend>Durée <span>(plusieurs choix possibles)</span></legend><div>{durationOptions.map(([value,label])=><button type="button" key={value} aria-pressed={duration.includes(value)} className={duration.includes(value)?"chosen":""} onClick={()=>toggleDuration(value)}>{label}</button>)}</div></fieldset><fieldset className="choice-filter"><legend>Difficulté <span>(plusieurs choix possibles)</span></legend><div>{difficultyOptions.map(([value,label])=><button type="button" key={value} aria-pressed={difficulty.includes(value)} className={difficulty.includes(value)?"chosen":""} onClick={()=>toggleDifficulty(value)}>{label}</button>)}</div></fieldset>{allTags.length>0&&<fieldset className="tag-filter"><legend>Types de jeu <span>(facultatif)</span></legend><div>{allTags.map(tag=>{const mode=tagFilters[tag];return <button type="button" key={tag} data-mode={mode||"neutral"} aria-label={`${tag}, ${mode==="include"?"inclus":mode==="exclude"?"exclu":"sans filtre"}`} onClick={()=>cycleTag(tag)}>{mode==="include"?"+ ":mode==="exclude"?"− ":""}{tag}</button>})}</div><small>1 appui pour inclure, 2 pour exclure, 3 pour enlever le filtre.</small></fieldset>}<button className="primary" onClick={pick}>Choisir un jeu <Dices size={20}/></button></section>{picked&&<section className="result" key={picked.id}><Cover game={picked} large/><h2>{picked.name}</h2><p>{picked.minPlayers} à {picked.maxPlayers} joueurs{picked.estimatedMinutes?` · ~ ${formatDuration(picked.estimatedMinutes)}`:""}{picked.avgDuration?` · ${formatDuration(picked.avgDuration)} chez nous`:""}</p><button className="primary" onClick={()=>{open(picked);setChosen([]);setPlayerSearch("");setPicker(true)}}>Jouer</button><button className="text-action" onClick={pick}>Un autre</button></section>}{!games.length&&<p className="muted">Chargement de la ludothèque…</p>}{games.length>0&&!compatible.length&&<p className="muted">Aucun jeu ne correspond à ces choix.</p>}</>}
      {tab==="games"&&<><header className="list-top"><h1>Nos jeux <small>({games.length})</small></h1><div><button onClick={()=>setSearchOpen(!searchOpen)} aria-label="Rechercher, filtrer ou trier les jeux"><Search/></button><button onClick={()=>openEditor("new")} aria-label="Ajouter un jeu"><Plus/></button></div></header>{searchOpen&&<div className="library-filters"><label className="search-field"><Search size={20}/><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} placeholder="Chercher un jeu…"/></label><fieldset className="choice-filter"><legend>Difficulté</legend><div>{difficultyOptions.map(([value,label])=><button type="button" key={value} aria-pressed={libraryDifficulty.includes(value)} className={libraryDifficulty.includes(value)?"chosen":""} onClick={()=>toggleLibraryDifficulty(value)}>{label}</button>)}</div></fieldset><fieldset className="choice-filter"><legend>Temps de jeu</legend><div>{durationOptions.map(([value,label])=><button type="button" key={value} aria-pressed={libraryDuration.includes(value)} className={libraryDuration.includes(value)?"chosen":""} onClick={()=>toggleLibraryDuration(value)}>{label}</button>)}</div></fieldset><label className="filter-select">Joueurs<select value={libraryPlayers??""} onChange={event=>setLibraryPlayers(event.target.value?Number(event.target.value):null)}><option value="">Peu importe</option>{[2,3,4,5,6,7,8].map(value=><option key={value} value={value}>{value===8?"8+":value}</option>)}</select></label><label className="filter-select">Trier par<select value={librarySort} onChange={event=>setLibrarySort(event.target.value as LibrarySort)}><option value="name">Alphabétique</option><option value="difficulty">Difficulté</option><option value="time">Temps de jeu</option><option value="players">Nombre de joueurs</option></select></label></div>}<div className="game-grid">{visibleGames.map(game=><button key={game.id} className="game-tile" onClick={()=>open(game)}><Cover game={game}/><span>{game.name}</span>{game.tags.length>0&&<small className="game-tile-tags">{game.tags.join(" · ")}</small>}</button>)}</div>{!visibleGames.length&&<p className="muted">Aucun jeu ne correspond à ces filtres.</p>}</>}
      {tab==="stats"&&<section className="stats"><h1>Stats</h1><label className="filter-select player-stats-select">Voir les statistiques de<select value={selectedStatsPlayer??""} onChange={event=>setSelectedStatsPlayer(event.target.value?Number(event.target.value):null)}><option value="">Toute la famille</option>{players.map(player=><option key={player.id} value={player.id}>{player.name}</option>)}</select></label>{selectedStatsPlayer!==null&&playerStats?<><h2>{playerStats.player.name}</h2><strong>{plural(playerStats.total,"partie")} jouée{playerStats.total===1?"":"s"}</strong><p>{plural(playerStats.wins,"victoire")} · {playerStats.winRate.value||0} % de victoires</p><p>Temps total joué : <b>{formatDuration(playerStats.totalDuration.value)}</b></p>{playerStats.averageDuration.count?<p>Durée moyenne : <b>{formatDuration(playerStats.averageDuration.value!)}</b></p>:null}{playerStats.averageScore.count?<p>Score moyen : <b>{formatNumber(playerStats.averageScore.value!)}</b></p>:null}<h2>Ses jeux les plus joués</h2>{playerStats.games.length?playerStats.games.map(game=><div className="stat-row player-game-stat" key={game.id}><b>{game.name}</b><span>{plural(game.plays,"partie")} · {plural(game.wins,"victoire")}<br/>{formatDuration(game.totalDuration)} joué{game.averageDuration!==null?` · ${formatDuration(game.averageDuration)} / partie`:""}{game.scoreCount?` · score moyen ${formatNumber(game.averageScore!)}`:""}</span></div>):<p className="muted">Aucune partie enregistrée pour ce joueur.</p>}</>:<><strong>{plural(stats?.total||0,"partie")} jouée{stats?.total===1?"":"s"}</strong><p>{plural(stats?.totalWins||0,"victoire")} enregistrée{stats?.totalWins===1?"":"s"}</p><p>Temps total joué : <b>{formatDuration(stats?.totalDuration.value||0)}</b></p>{stats?.averageDuration.count?<p>Durée moyenne globale : <b>{formatDuration(stats.averageDuration.value!)}</b> <small>({plural(stats.averageDuration.count,"partie")} chronométrée{stats.averageDuration.count===1?"":"s"})</small></p>:null}{stats&&stats.topGames.length>0&&<><h2>Jeux les plus joués</h2>{stats.topGames.map(game=><div className="stat-row" key={game.name}><b>{game.name}</b><span>{plural(game.plays,"partie")}</span></div>)}</>}<h2>Les joueurs</h2>{stats?.players.map(player=><div className="stat-row" key={player.id}><b>{player.name}</b><span>{plural(player.plays,"partie")} · {plural(player.wins,"victoire")}{player.plays?` · ${player.winRate||0} % de victoires · ${formatDuration(player.totalDuration)} jouées`:""}</span></div>)}</>}</section>}
      {tab==="history"&&<section className="stats"><h1>Historique</h1>{!history.length&&<p className="muted">Aucune partie enregistrée.</p>}{history.map(play=><article className="history-play" key={play.id}><div><b>{play.gameName}</b><small>{new Date(play.playedAt+"Z").toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short"})}{play.duration?` · ${formatDuration(play.duration)}`:""}</small></div><button onClick={()=>openHistoryEdit(play)} aria-label={`Modifier la partie de ${play.gameName}`}><PenLine/></button><p>{play.participants.map(participant=>`${participant.winner?"★ ":" "}${participant.name}${participant.score!==null?` (${participant.score})`:""}`).join(" · ")}</p>{play.events.length>0&&<p className="muted">{play.events.map(event=>`${event.name}${event.playerName?` · ${event.playerName}`:""} ×${event.count}`).join(" · ")}</p>}{play.notes&&<small>{play.notes}</small>}</article>)}</section>}
      <nav className="bottom-nav" aria-label="Navigation principale"><button aria-current={tab==="play"?"page":undefined} className={tab==="play"?"active":""} onClick={()=>setTab("play")}><Dices/>Jouer</button><button aria-current={tab==="games"?"page":undefined} className={tab==="games"?"active":""} onClick={()=>setTab("games")}><LibraryBig/>Jeux</button><button aria-current={tab==="history"?"page":undefined} className={tab==="history"?"active":""} onClick={()=>setTab("history")}><Clock3/>Historique</button><button aria-current={tab==="stats"?"page":undefined} className={tab==="stats"?"active":""} onClick={()=>setTab("stats")}><ChartNoAxesColumnIncreasing/>Stats</button></nav>
    </>}

    {picker&&<div className="sheet-backdrop" onClick={()=>setPicker(false)}><div className="sheet player-sheet" role="dialog" aria-modal="true" aria-labelledby="picker-title" onClick={event=>event.stopPropagation()}><button className="sheet-close" onClick={()=>setPicker(false)} aria-label="Fermer"><X/></button><h2 id="picker-title">Qui joue ?</h2>{chosen.length>0&&<div className="selected-players" aria-label="Participants choisis">{chosen.map(id=><button key={id} onClick={()=>setChosen(current=>current.filter(item=>item!==id))}>{players.find(player=>player.id===id)?.name}<X/></button>)}</div>}<label className="search-field player-search"><Search/><input value={playerSearch} onChange={event=>setPlayerSearch(event.target.value)} placeholder="Chercher un joueur connu…" aria-label="Chercher un joueur connu"/></label><div className="known-player-list">{availablePlayers.map(player=><button key={player.id} onClick={()=>{setChosen(current=>[...current,player.id]);setPlayerSearch("")}}><span>{player.name}</span><Plus/></button>)}</div>{players.length>0&&!availablePlayers.length&&<p className="muted player-empty">Aucun autre joueur trouvé.</p>}<form className="add-player" onSubmit={addPlayer}><input value={newPlayer} onChange={event=>setNewPlayer(event.target.value)} placeholder="Ajouter un nouveau prénom" aria-label="Nouveau joueur"/><button type="submit" aria-label="Ajouter le joueur"><Plus/></button></form><button className="primary" disabled={!chosen.length} onClick={start}>Commencer avec le chrono</button><button className="text-action" disabled={!chosen.length} onClick={recordFinished}>Noter une partie déjà terminée</button></div></div>}

    {finishing&&session&&<div className="sheet-backdrop" onClick={()=>setFinishing(false)}><div className="sheet" role="dialog" aria-modal="true" aria-labelledby="winner-title" onClick={event=>event.stopPropagation()}><button className="sheet-close" onClick={()=>setFinishing(false)} aria-label="Fermer"><X/></button><h2 id="winner-title">Qui a gagné ?</h2><p className="finished-time">Durée : {session.tracking?elapsed(secondsIn(session)):"non enregistrée"}</p><div className="player-grid">{session.players.map(id=>{const player=players.find(item=>item.id===id);return <button key={id} aria-pressed={winners.includes(id)} className={winners.includes(id)?"chosen":""} onClick={()=>setWinners(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])}>{player?.name||"Joueur"}</button>})}</div><fieldset className="scores"><legend>Scores <span>(facultatifs{selected?.lowerScoreWins?" · le plus petit gagne":""})</span></legend>{session.players.map(id=><label key={id}><span>{players.find(player=>player.id===id)?.name||"Joueur"}</span><input type="text" inputMode="text" value={scores[id]||""} onChange={event=>setScores(current=>({...current,[id]:event.target.value}))} placeholder="Score"/></label>)}</fieldset><p className="muted">Événements notés : {session.events.length}</p><button className="primary" disabled={busy} onClick={savePlay}>Enregistrer la partie</button></div></div>}

    {editingHistory&&<div className="sheet-backdrop" onClick={()=>setEditingHistory(null)}><form className="sheet form-sheet" role="dialog" aria-modal="true" aria-labelledby="history-edit-title" onClick={event=>event.stopPropagation()} onSubmit={saveHistory}><button type="button" className="sheet-close" onClick={()=>setEditingHistory(null)} aria-label="Fermer"><X/></button><h2 id="history-edit-title">Modifier la partie</h2><p className="muted">{editingHistory.gameName} · {new Date(editingHistory.playedAt+"Z").toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short"})}</p><label>Durée (minutes)<input name="duration" type="number" min="1" defaultValue={editingHistory.duration||""} placeholder="Non enregistrée"/></label><fieldset className="editor-tags"><legend>Participants</legend><div className="editor-tag-list">{players.map(player=><button type="button" key={player.id} aria-pressed={historyPlayers.includes(player.id)} className={historyPlayers.includes(player.id)?"chosen":""} onClick={()=>setHistoryPlayers(current=>current.includes(player.id)?current.filter(id=>id!==player.id):[...current,player.id])}>{historyPlayers.includes(player.id)?"✓ ":""}{player.name}</button>)}</div></fieldset><fieldset className="scores"><legend>Gagnants et scores <span>(facultatifs)</span></legend>{historyPlayers.map(id=><label key={id}><button type="button" className={winners.includes(id)?"chosen":""} onClick={()=>setWinners(current=>current.includes(id)?current.filter(playerId=>playerId!==id):[...current,id])}>{winners.includes(id)?"★ ":""}{players.find(player=>player.id===id)?.name}</button><input type="text" inputMode="text" value={scores[id]||""} onChange={event=>setScores(current=>({...current,[id]:event.target.value}))} placeholder="Score" aria-label={`Score de ${players.find(player=>player.id===id)?.name||"Joueur"}`}/></label>)}</fieldset><label>Note<textarea name="notes" rows={3} defaultValue={editingHistory.notes||""}/></label><button className="primary" disabled={busy||!historyPlayers.length}>Enregistrer les corrections</button></form></div>}

    {replayPrompt&&lastPlay&&<div className="sheet-backdrop"><div className="sheet replay-sheet" role="dialog" aria-modal="true" aria-labelledby="replay-title"><h2 id="replay-title">Partie enregistrée</h2><p>Vous en refaites une avec les mêmes joueurs ?</p><button className="primary" onClick={replay}>Rejouer</button><button className="text-action" onClick={()=>setReplayPrompt(false)}>Terminé</button></div></div>}

    {editor&&<div className="sheet-backdrop" onClick={()=>setEditor(null)}><form className="sheet form-sheet" role="dialog" aria-modal="true" aria-labelledby="editor-title" onClick={event=>event.stopPropagation()} onSubmit={saveGame}>
      <button type="button" className="sheet-close" onClick={()=>setEditor(null)} aria-label="Fermer"><X/></button><h2 id="editor-title">{editor==="new"?"Ajouter un jeu":"Modifier le jeu"}</h2>
      <label>Nom<input name="name" required defaultValue={editor==="edit"?selected?.name:""}/></label><label>Photo de la boîte<input name="coverFile" type="file" accept="image/jpeg,image/png,image/webp"/></label>
      <div className="two-fields"><label>Joueurs min<input name="min" type="number" min="1" required defaultValue={editor==="edit"?selected?.minPlayers:2}/></label><label>Joueurs max<input name="max" type="number" min="1" required defaultValue={editor==="edit"?selected?.maxPlayers:4}/></label></div>
      <label>Durée approximative (min)<input name="minutes" type="number" min="1" defaultValue={editor==="edit"?selected?.estimatedMinutes||"":""}/></label><label><input name="lowerScoreWins" type="checkbox" defaultChecked={editor==="edit"&&selected?.lowerScoreWins}/> Le plus petit score gagne</label><label className="difficulty-slider">Difficulté <span>{formatNumber(editingDifficulty)}/5 · {difficultyLabel(editingDifficulty)}</span><input name="difficulty" type="range" min="0" max="5" step="0.1" value={editingDifficulty} onChange={event=>setEditingDifficulty(Number(event.target.value))}/></label><label>Notre note / 5<input name="rating" type="number" min="1" max="5" defaultValue={editor==="edit"?selected?.rating||"":""}/></label>
      <fieldset className="editor-tags"><legend>Tags</legend><div className="editor-tag-list">{editorTagChoices.map(tag=><button type="button" key={tag} aria-pressed={editingTags.includes(tag)} className={editingTags.includes(tag)?"chosen":""} onClick={()=>toggleEditingTag(tag)}>{editingTags.includes(tag)?"✓ ":""}{tag}</button>)}</div><label>Nouveau tag<div className="new-tag"><input value={newTag} onChange={event=>setNewTag(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();addEditingTag()}}} placeholder="Ex. Jeu coopératif"/><button type="button" onClick={addEditingTag} disabled={!newTag.trim()} aria-label="Ajouter ce tag"><Plus/></button></div></label></fieldset>
      <label>Lien des règles<input name="rulesUrl" type="url" defaultValue={editor==="edit"?selected?.rulesUrl||"":""} placeholder="https://…"/></label><label>Notes<textarea name="notes" rows={2} defaultValue={editor==="edit"?selected?.notes||"":""}/></label><button className="primary" disabled={busy}>{editor==="new"?"Ajouter le jeu":"Enregistrer"}</button>{editor==="edit"&&<button type="button" className="remove-game" onClick={removeGame}><Trash2 size={18}/> Retirer ce jeu</button>}
    </form></div>}

    {addingRule&&<div className="sheet-backdrop" onClick={()=>setAddingRule(false)}><form className="sheet form-sheet" role="dialog" aria-modal="true" aria-labelledby="rule-title" onClick={event=>event.stopPropagation()} onSubmit={addRule}><button type="button" className="sheet-close" onClick={()=>setAddingRule(false)} aria-label="Fermer"><X/></button><h2 id="rule-title">Ajouter une règle</h2><label>Section<input name="title" required placeholder="Mise en place, échanges…"/></label><label>Texte<textarea name="content" required rows={8}/></label><button className="primary" disabled={busy}>Enregistrer</button></form></div>}
  </main>;
}

function Highlight({text,query}:{text:string;query:string}) {const term=query.trim().split(/\s+/)[0];if(!term)return text;const index=text.toLocaleLowerCase("fr").indexOf(term.toLocaleLowerCase("fr"));if(index<0)return text.length>360?`${text.slice(0,360)}…`:text;const from=Math.max(0,index-100),to=Math.min(text.length,index+term.length+220);return <>{from>0&&"…"}{text.slice(from,index)}<mark>{text.slice(index,index+term.length)}</mark>{text.slice(index+term.length,to)}{to<text.length&&"…"}</>}
