import { db } from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";
export const dynamic="force-dynamic";
type Session={gameId:number;players:number[];startedAt:number|null;elapsedSeconds:number;tracking:boolean;paused:boolean;events:{eventId:number;playerId:number}[];version:number};
const read=()=>{const row=db.prepare("SELECT gameId,players,startedAt,elapsedSeconds,tracking,paused,events,version FROM active_session WHERE id=1").get() as any;if(!row)return null;try{return {...row,players:JSON.parse(row.players),events:JSON.parse(row.events),tracking:!!row.tracking,paused:!!row.paused} as Session}catch{return null}};
const valid=(value:any):value is Omit<Session,"version"> & {expectedVersion:number}=>Number.isInteger(value?.gameId)&&Array.isArray(value.players)&&value.players.length>0&&new Set(value.players).size===value.players.length&&value.players.every(Number.isInteger)&&(value.startedAt===null||Number.isInteger(value.startedAt))&&Number.isInteger(value.elapsedSeconds)&&value.elapsedSeconds>=0&&typeof value.tracking==="boolean"&&typeof value.paused==="boolean"&&Array.isArray(value.events)&&value.events.every((e:any)=>Number.isInteger(e.eventId)&&Number.isInteger(e.playerId)&&value.players.includes(e.playerId));
export async function GET(){return NextResponse.json(read())}
export async function PUT(request:NextRequest){const body:any=await request.json();if(!valid(body)||!Number.isInteger(body.expectedVersion))return NextResponse.json({error:"Session invalide."},{status:400});const game=db.prepare("SELECT id FROM games WHERE id=?").get(body.gameId);const playerCount=db.prepare(`SELECT count(*) count FROM players WHERE id IN (${body.players.map(()=>"?").join(",")})`).get(...body.players) as {count:number};if(!game||playerCount.count!==body.players.length)return NextResponse.json({error:"Jeu ou joueur introuvable."},{status:400});const current=read();if(current&&current.version!==body.expectedVersion)return NextResponse.json({error:"La partie a été modifiée sur un autre téléphone.",session:current},{status:409});const version=(current?.version||0)+1;db.prepare("INSERT INTO active_session(id,gameId,players,startedAt,elapsedSeconds,tracking,paused,events,version,updatedAt) VALUES(1,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET gameId=excluded.gameId,players=excluded.players,startedAt=excluded.startedAt,elapsedSeconds=excluded.elapsedSeconds,tracking=excluded.tracking,paused=excluded.paused,events=excluded.events,version=excluded.version,updatedAt=excluded.updatedAt").run(body.gameId,JSON.stringify(body.players),body.startedAt,body.elapsedSeconds,body.tracking?1:0,body.paused?1:0,JSON.stringify(body.events),version,Date.now());return NextResponse.json({...body,version})}
export async function DELETE(request:NextRequest){const expectedVersion=Number(request.nextUrl.searchParams.get("expectedVersion")),current=read();if(!current)return NextResponse.json({error:"La partie est déjà terminée ou annulée.",session:null},{status:409});if(!Number.isInteger(expectedVersion)||expectedVersion!==current.version)return NextResponse.json({error:"La partie a été modifiée sur un autre téléphone.",session:current},{status:409});db.prepare("DELETE FROM active_session WHERE id=1").run();return new NextResponse(null,{status:204})}
